# Generated by Django 4.2.2 on 2023-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whats_app_link', models.URLField(max_length=300)),
                ('telegram_link', models.URLField(max_length=300)),
                ('viber_link', models.URLField(max_length=300)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
