# Generated by Django 4.2.2 on 2023-06-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contats',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
