# Generated by Django 4.2.2 on 2023-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_home_page_heading_text_alter_home_page_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='contats',
            name='instagram_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contats',
            name='vk_group_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contats',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contats',
            name='telegram_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contats',
            name='viber_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contats',
            name='whats_app_link',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
