# Generated by Django 4.2.2 on 2023-06-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contats_instagram_link_contats_vk_group_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='description_1_text_left',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_1_text_right',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_1_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_2_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_2_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_3_text_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_3_text_2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_3_text_3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='home_page',
            name='description_3_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='heading_text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
